// AUTO-GENERATED by ts-rs from Rust contracts. DO NOT EDIT.
// Re-generate: ./gen_types.sh ./bindings ../frontend/src/lib/types.generated.ts


export type AgentInfo = { type: AgentType, name: string, image: string, };


export type AgentType = "claude_code" | "codex";


export type ConfigItem = { key: string, value: string, encrypted: boolean, };


export type CreateTaskRequest = { title: string, prompt: string, repo_url: string | null, branch: string | null, agent_type: AgentType | null, model: string | null, };


export type CreateTaskResponse = { id: string, status: TaskStatus, created_at: string, };


export type SettingsResponse = { agents: Array<AgentInfo>, default_model: string, config: Array<ConfigItem>, };


export type Task = { id: string, title: string, prompt: string, repo_url: string | null, branch: string | null, agent_type: AgentType, model: string, status: TaskStatus, container_id: string | null, agent_exit_code: number | null, duration_seconds: number | null, pushed: boolean, lines_added: number, lines_removed: number, files_changed: string | null, summary: string | null, diff_patch: string | null, error: string | null, created_at: string, started_at: string | null, finished_at: string | null, };


export type TaskListResponse = { tasks: Array<Task>, total: number, };


export type TaskLogsResponse = { logs: string, };


export type TaskStatus = "pending" | "running" | "success" | "failed" | "cancelled";


export type TestResult = { success: boolean, message: string, };


export type UpdateSettingsRequest = { config: Array<ConfigItem>, };

